#!/bin/sh

tools/parser.py examples/xml/amfoot-match-classic-generic.xml >examples/json/amfoot-match-classic-generic.json
tools/parser.py examples/xml/amfoot-match-classic-specific.xml >examples/json/amfoot-match-classic-specific.json
tools/parser.py examples/xml/amfoot-match-g2-generic.xml >examples/json/amfoot-match-g2-generic.json
tools/parser.py examples/xml/amfoot-match-g2-specific.xml >examples/json/amfoot-match-g2-specific.json
tools/parser.py examples/xml/baseball-match-classic-generic.xml >examples/json/baseball-match-classic-generic.json
tools/parser.py examples/xml/baseball-match-classic-specific.xml >examples/json/baseball-match-classic-specific.json
tools/parser.py examples/xml/baseball-match-g2-generic.xml >examples/json/baseball-match-g2-generic.json
tools/parser.py examples/xml/baseball-match-g2-specific.xml >examples/json/baseball-match-g2-specific.json
tools/parser.py examples/xml/basketball-match-classic-generic.xml >examples/json/basketball-match-classic-generic.json
tools/parser.py examples/xml/basketball-match-classic-specific.xml >examples/json/basketball-match-classic-specific.json
tools/parser.py examples/xml/basketball-match-g2-generic.xml >examples/json/basketball-match-g2-generic.json
tools/parser.py examples/xml/basketball-match-g2-specific.xml >examples/json/basketball-match-g2-specific.json
tools/parser.py examples/xml/biathlon_mixedrelay_g2.xml >examples/json/biathlon_mixedrelay_g2.json
tools/parser.py examples/xml/curling_worlds_tournament.xml >examples/json/curling_worlds_tournament.json
tools/parser.py examples/xml/golf-tour.xml >examples/json/golf-tour.json
tools/parser.py examples/xml/ice-hockey-match-classic-generic.xml >examples/json/ice-hockey-match-classic-generic.json
tools/parser.py examples/xml/ice-hockey-match-classic-specific.xml >examples/json/ice-hockey-match-classic-specific.json
tools/parser.py examples/xml/ice-hockey-match-g2-generic.xml >examples/json/ice-hockey-match-g2-generic.json
tools/parser.py examples/xml/ice-hockey-match-g2-specific.xml >examples/json/ice-hockey-match-g2-specific.json
tools/parser.py examples/xml/ice-hockey-plays-classic-generic.xml >examples/json/ice-hockey-plays-classic-generic.json
tools/parser.py examples/xml/ice-hockey-plays-classic-specific.xml >examples/json/ice-hockey-plays-classic-specific.json
tools/parser.py examples/xml/ice-hockey-plays-g2-generic.xml >examples/json/ice-hockey-plays-g2-generic.json
tools/parser.py examples/xml/ice-hockey-plays-g2-specific.xml >examples/json/ice-hockey-plays-g2-specific.json
tools/parser.py examples/xml/ice-hockey-roster-classic.xml >examples/json/ice-hockey-roster-classic.json
tools/parser.py examples/xml/ice-hockey-roster-g2.xml >examples/json/ice-hockey-roster-g2.json
tools/parser.py examples/xml/ice-hockey-standings-classic-generic.xml >examples/json/ice-hockey-standings-classic-generic.json
tools/parser.py examples/xml/ice-hockey-standings-classic-specific.xml >examples/json/ice-hockey-standings-classic-specific.json
tools/parser.py examples/xml/ice-hockey-standings-g2-generic.xml >examples/json/ice-hockey-standings-g2-generic.json
tools/parser.py examples/xml/ice-hockey-standings-g2-specific.xml >examples/json/ice-hockey-standings-g2-specific.json
tools/parser.py examples/xml/rugby-match-classic-generic-3.0.xml >examples/json/rugby-match-classic-generic-3.0.json
tools/parser.py examples/xml/rugby-match-g2-generic-3.0.xml >examples/json/rugby-match-g2-generic-3.0.json
tools/parser.py examples/xml/skiing_vasaloppet_2015_g2.xml >examples/json/skiing_vasaloppet_2015_g2.json
tools/parser.py examples/xml/soccer-match-classic-generic.xml >examples/json/soccer-match-classic-generic.json
tools/parser.py examples/xml/soccer-match-classic-specific.xml >examples/json/soccer-match-classic-specific.json
tools/parser.py examples/xml/soccer-match-g2-generic.xml >examples/json/soccer-match-g2-generic.json
tools/parser.py examples/xml/soccer-match-g2-specific.xml >examples/json/soccer-match-g2-specific.json
tools/parser.py examples/xml/soccer-season-stats-classic-generic.xml >examples/json/soccer-season-stats-classic-generic.json
tools/parser.py examples/xml/soccer-season-stats-classic-specific.xml >examples/json/soccer-season-stats-classic-specific.json
tools/parser.py examples/xml/soccer-season-stats-g2-generic.xml >examples/json/soccer-season-stats-g2-generic.json
tools/parser.py examples/xml/soccer-season-stats-g2-specific.xml >examples/json/soccer-season-stats-g2-specific.json
tools/parser.py examples/xml/soccer-standings-classic-specific.xml >examples/json/soccer-standings-classic-specific.json
tools/parser.py examples/xml/soccer-standings-g2-specific.xml >examples/json/soccer-standings-g2-specific.json
tools/parser.py examples/xml/tennis_davis_cup_tournament.xml >examples/json/tennis_davis_cup_tournament.json
tools/parser.py examples/xml/tournament-cl-classic.xml >examples/json/tournament-cl-classic.json
tools/parser.py examples/xml/tournament-cl-g2.xml >examples/json/tournament-cl-g2.json
