#!/bin/sh

jsonschema -i examples/json/amfoot-match-classic-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/amfoot-match-classic-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/amfoot-match-classic-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/amfoot-match-g2-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/amfoot-match-g2-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/baseball-match-classic-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/baseball-match-classic-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/baseball-match-g2-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/baseball-match-g2-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/basketball-match-classic-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/basketball-match-classic-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/basketball-match-g2-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/basketball-match-g2-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/biathlon_mixedrelay_g2.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/curling_worlds_tournament.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/esports-match-g2-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/golf-tour.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-match-classic-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-match-classic-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-match-g2-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-match-g2-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-plays-classic-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-plays-classic-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-plays-g2-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-plays-g2-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-roster-classic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-roster-g2.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-standings-classic-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-standings-classic-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-standings-g2-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/ice-hockey-standings-g2-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/rugby-match-classic-generic-3.0.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/rugby-match-g2-generic-3.0.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/skiing_vasaloppet_2015_g2.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/soccer-match-classic-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/soccer-match-classic-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/soccer-match-g2-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/soccer-match-g2-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/soccer-season-stats-classic-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/soccer-season-stats-classic-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/soccer-season-stats-g2-generic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/soccer-season-stats-g2-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/soccer-standings-classic-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/soccer-standings-g2-specific.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/tennis_davis_cup_tournament.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/tournament-cl-classic.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
jsonschema -i examples/json/tournament-cl-g2.json ../../sportsjs-dev/specification/strict/sportsjs-core.json
